# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
     - 'v*' 
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: '0'
      - id: tag_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Got tag name ${{ steps.tag_version.outputs.tag }}"
#        run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false
#       - name: Publish to GitHub Packages Apache Maven
#         run: mvn -B deploy -DskipTests --file pom.xml
#         env:
#           GITHUB_TOKEN: ${{ github.token }}
          
#       - name: Create GitHub release
#         uses: elgohr/Github-Release-Action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#         with: 
#           tag_name: ${{github.run_number}}
#           release_name: Release ${{github.run_number}} 
